accounts/urls.py
from django.urls import path
from .import views

app_name = "Account"

urlpatterns = [
    path("profile/", views.profile, name="profile"),
    path("apply/", views.be_seller, name="apply"),
]

api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    # Medicines
    path('', views.MedicineView.as_view(), name="APIv1"),
    path('detail/<int:pk>/', views.APIDetailView.as_view(), name="medicine_detail"),
    path('detail/<str:slug>/', views.APIDetailView.as_view(), name="medicine_detail"),

    # Regarding user details
    path('user/', views.get_current_user, name="user"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('login/', views.APILoginView.as_view(), name="login"),
    path('logout/', views.api_logout, name="logout"),
    path('register/', views.APISignupView.as_view(), name='register'),
    path('sell/', views.SellerView.as_view(), name='sell'),

    # Cart, Orders related views
    path('cart/', views.CartView.as_view(), name='cart'),
    path('orders/', views.OrderView.as_view(), name='orders'),
    path('address/', views.APIBillingAddress.as_view(), name='orders'),
]

cart/urls.py
from django.urls import path
from .views import cartview, add_to_cart, remove_from_cart
from . import views

app_name = "cart"

urlpatterns = [
    path("cart/", cartview, name="home"),
    path("add/<slug>", add_to_cart, name="add"),
    path("remove/<slug>", remove_from_cart, name="remove"),
    path("increase/<slug>", views.increase_cart_test, name="increase"),
    path("decrease/<slug>", views.decrease_cart_test, name="decrease"),
    path("orders/", views.order_view, name="my_orders")
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from.views import HomeView

app_name = 'home'

urlpatterns = [
    path("", HomeView.as_view(), name='home'),
    path(r'service-worker.js', (TemplateView.as_view(
        template_name="sw.js",
        content_type='application/javascript',
    )), name='service-worker.js')
]

medical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from medicines.sitemaps import MedSiteMap
from accounts.sitemaps import AccountSiteMap
from django.views.generic import TemplateView
from .sitemaps import StaticSitemap


sitemaps = {
    'accounts': AccountSiteMap,
    'medicines': MedSiteMap,
    'other': StaticSitemap
}

urlpatterns = [
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots"),
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name="sitemap_url"),
    path("", include("home.urls")),
    path("", include("cart.urls")),
    path('admin/', admin.site.urls),
    path('medicines/', include("medicines.urls")),
    path("", include("checkout.urls")),
    path("", include("accounts.urls")),
    path("", include("allauth.urls")),
    path("api/v1/", include("api.urls")),
]

home/forms.py
from allauth.account.forms import SignupForm
from django import forms


class UserSignUp(SignupForm):
    first_name = forms.CharField(max_length=10)
    last_name = forms.CharField(max_length=15)

    def signup(self, user):
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        return user

home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings
# Create your views here.


class HomeView(View):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.dev_env = settings.DEBUG

    def get(self, request, ):
        ctx = {
            "Dev_Env": self.dev_env,
        }
        return render(request, "home/main.html", ctx)

home/templates/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<!--suppress ALL -->
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width= device-width,initial-scale=1.0"/>
    <link href="/static/manifest.json" rel="manifest">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
          crossorigin="anonymous">
    <link rel="icon" href="{%static 'favicon.ico' %}">
<style>
    html, body{height: 100%;}
        body{background: #efefef; overflow-x: hidden;max-width: 100vw;
        display: flex; flex-direction: column;}
        body>*{flex: 1 0 auto;}
        footer{flex-shrink: 0; flex-grow: 0}
        .btn-danger,.btn-default,.btn-info,.btn-primary,.btn-success,.btn-warning {
            text-shadow: 0 -1px 0 rgba(0,0,0,.2);
            -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,.15),0 1px 1px rgba(0,0,0,.075);
            box-shadow: inset 0 1px 0 rgba(255,255,255,.15),0 1px 1px rgba(0,0,0,.075)
        }
        .btn-primary {
            background-image: -webkit-linear-gradient(top,#337ab7 0,#265a88 100%);
            background-image: -o-linear-gradient(top,#337ab7 0,#265a88 100%);
            background-image: -webkit-gradient(linear,left top,left bottom,from(#337ab7),to(#265a88));
            background-image: linear-gradient(to bottom,#337ab7 0,#265a88 100%);
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff337ab7', endColorstr='#ff265a88', GradientType=0);
            background-repeat: repeat-x;
            border-color: #245580
        }
        .btn-primary:focus,.btn-primary:hover {
            background-color: #265a88;
            background-position: 0 -15px
        }
        .navbar-brand,.navbar-nav>li>a {
            text-shadow: 0 1px 0 rgba(255,255,255,.25)
        }
        {% if not user.is_authenticated%}
        .btn-pre{
            position: absolute;
            padding: 5px 20px !important;
            left: 42%;
            border-radius: 25px;
        }
        {% endif %}
        {# Footer specific#}
    footer{background: #333;}
    footer aside{display: flex; justify-content: space-around; padding: 1em;}
    footer button{padding: .5em;border: none; background: transparent; position: relative; color: #fff}
    footer button::before{position: absolute; content: ""; width: 0; height: 100%; background: #fee;}
    svg{height: 2em; margin: 0;}
    footer button:hover::before{width: 100%; transition: 500ms;opacity: .2;left: 50%; top: 50%; transform: translate(-50%, -50%);}
    </style>

    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous"/>

    {% block head %} {% endblock %}

    <style>
    #preloader, #quickloader {
        border: 16px solid #f3f3f3; /* Light grey */
        position: fixed;
        border-top: 16px solid #3498db; /* Blue */
        border-radius: 50%;
        left: 45%;
        right: 45%;
        top: 40vh;
        width: 120px;
        height: 120px;
        animation: spin 2s linear infinite;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
    .asteriskField{
        color: red;
    }
    </style>
</head>
<body>
{%block preloader%}
    <span id="quickloader" style="width: 50px; height: 50px; display: none; z-index:3"></span>
    <div id="preloader" style="z-index: 2;"></div>
{%endblock%}

<div class="container next" style="display:none">
{% block navbar %}
    {% include 'header.html' %}
    {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    <div class="messages container mt-2">
        {%if messages%}
            {% for message in messages %}
            <div {% if message.tags == 'error' %} class="alert alert-danger" {%else%} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
        {% endif %}
    </div>
    {% endblock %}
    {% block content %}
    {% endblock %}
</div>
{% block footer %} {% include 'footer.html' %} {% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
{%block js%}
{%endblock%}
<script>
    window.addEventListener('load', _=>{
        const preloader = document.getElementById("preloader");
        const page = document.getElementsByClassName("next")[0];
        preloader.style.display = "none"
        page.style.display = "";

        const links = document.querySelectorAll("[data-take-me]");
        links.forEach(link=>{
            link.addEventListener('click', function(){
                const url = this.dataset.takeMe;
                url.startsWith('http')?
                window.open(this.dataset.takeMe, '_blank')
                :
                location.replace(location.protocol + "//" + location.host + url);
            })
        })

        if('serviceWorker' in navigator){
            navigator.serviceWorker.register('/service-worker.js').then(reg=>{
                console.log('Service worker registerd!! Scope: ', reg.scope);
            }).catch(err=>{
                console.log("registration failed");
            })
        }

    })
</script>
</body>
</html>

home/templates/footer.html
{% load static %}
<footer>
    <aside>
        <button data-take-me="">View code on
            <svg focusable="false" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512">
                <path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path>
            </svg>
        </button>

        <button data-take-me="https://djangoproject.com/">Made with
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 436.506 152.503">
            <g fill="currentColor">
                <path d="M51.465 0h23.871v110.496c-12.245 2.325-21.236 3.256-31.002 3.256C15.191 113.75 0 100.576 0 75.308c0-24.337 16.122-40.147 41.078-40.147 3.875 0 6.82.309 10.387 1.239V0zm0 55.62c-2.79-.929-5.115-1.239-8.061-1.239-12.091 0-19.067 7.441-19.067 20.461 0 12.712 6.666 19.687 18.912 19.687 2.635 0 4.806-.154 8.216-.619V55.62z"></path>
                <path d="M113.312 36.865v55.338c0 19.067-1.396 28.213-5.58 36.118-3.876 7.597-8.992 12.401-19.532 17.673l-22.167-10.541c10.541-4.961 15.656-9.3 18.911-15.968 3.411-6.819 4.497-14.726 4.497-35.497V36.865h23.871zM89.441.127h23.871v24.492H89.441V.127zM127.731 42.29c10.542-4.959 20.617-7.129 31.623-7.129 12.246 0 20.306 3.254 23.872 9.61 2.014 3.565 2.634 8.215 2.634 18.137v48.517c-10.697 1.55-24.182 2.636-34.102 2.636-19.996 0-28.988-6.978-28.988-22.478 0-16.743 11.936-24.493 41.233-26.974v-5.27c0-4.34-2.17-5.889-8.216-5.889-8.835 0-18.756 2.48-28.058 7.286l.002-18.446zm37.359 37.978c-15.812 1.55-20.928 4.03-20.928 10.231 0 4.649 2.946 6.819 9.456 6.819 3.566 0 6.82-.309 11.471-1.084l.001-15.966zM197.487 40.585c14.105-3.72 25.731-5.424 37.512-5.424 12.246 0 21.082 2.789 26.354 8.215 4.96 5.114 6.509 10.694 6.509 22.632v46.812H243.99V66.938c0-9.145-3.1-12.557-11.625-12.557-3.255 0-6.2.31-11.007 1.705v56.734h-23.871V40.585zM277.142 125.841c8.372 4.341 16.742 6.354 25.577 6.354 15.654 0 22.32-6.354 22.32-21.546v-.465c-4.649 2.324-9.301 3.255-15.5 3.255-20.927 0-34.26-13.796-34.26-35.651 0-27.129 19.688-42.474 54.564-42.474 10.231 0 19.688 1.084 31.158 3.409l-8.174 17.219c-6.355-1.24-.509-.166-5.312-.631v2.481l.309 10.074.154 13.022c.155 3.254.155 6.51.311 9.765v6.512c0 20.461-1.705 30.071-6.819 37.977-7.441 11.627-20.308 17.361-38.599 17.361-9.301 0-17.359-1.395-25.731-4.65l.002-22.012zm47.434-71.305h-2.479c-4.649-.155-10.074 1.084-13.796 3.409-5.734 3.256-8.682 9.147-8.682 17.517 0 11.937 5.893 18.757 16.433 18.757 3.255 0 5.891-.621 8.989-1.55v-8.215c0-2.791-.153-5.893-.153-9.146l-.154-11.005-.156-7.906-.002-1.861zM398.062 34.85c23.871 0 38.443 15.037 38.443 39.373 0 24.958-15.19 40.614-39.373 40.614-23.873 0-38.6-15.037-38.6-39.218.002-25.114 15.194-40.769 39.53-40.769zm-.467 60.764c9.146 0 14.572-7.596 14.572-20.772 0-13.02-5.271-20.771-14.415-20.771-9.457 0-14.884 7.597-14.884 20.771.002 13.177 5.428 20.772 14.727 20.772z"></path>
            </g>
        </svg></button>
    </aside>
</footer>

home/templates/header.html
{% load cart_tag %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
  <a class="navbar-brand" href="/">MedStore</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'cart:home' %}">
          <svg style="height: 1em;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M528.12 301.319l47.273-208C578.806 78.301 567.391 64 551.99 64H159.208l-9.166-44.81C147.758 8.021 137.93 0 126.529 0H24C10.745 0 0 10.745 0 24v16c0 13.255 10.745 24 24 24h69.883l70.248 343.435C147.325 417.1 136 435.222 136 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-15.674-6.447-29.835-16.824-40h209.647C430.447 426.165 424 440.326 424 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-22.172-12.888-41.332-31.579-50.405l5.517-24.276c3.413-15.018-8.002-29.319-23.403-29.319H218.117l-6.545-32h293.145c11.206 0 20.92-7.754 23.403-18.681z">Cart</path></svg> Cart
          <span class="badge badge-light">{{ request.user| cart_total }}</span>
        </a>
      </li>
       <li class="nav-item">

      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <svg style="height: 1em;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm95.8 32.6L272 480l-32-136 32-56h-96l32 56-32 136-47.8-191.4C56.9 292 0 350.3 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-72.1-56.9-130.4-128.2-133.8z">Icon</path></svg> {{ request.user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/">Dashboard</a>
          <a class="dropdown-item" href="{% url 'cart:my_orders' %}">Orders</a>
          <a class="dropdown-item" href="{% url 'Account:profile' %}">Profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
        </div>
      </li>
      {% else %}
       <li class="nav-item">
        <a id="log" class="btn-pre btn btn-primary" href="{% url 'account_login' %}">Login / Register</a>
      </li>
      {% endif %}
    </ul>
  </div>
  </div>
</nav>