accounts/urls.py
from django.urls import path
from .import views

app_name = "Account"

urlpatterns = [
    path("profile/", views.profile, name="profile"),
    path("apply/", views.be_seller, name="apply"),
]

api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    # Medicines
    path('', views.MedicineView.as_view(), name="APIv1"),
    path('detail/<int:pk>/', views.APIDetailView.as_view(), name="medicine_detail"),
    path('detail/<str:slug>/', views.APIDetailView.as_view(), name="medicine_detail"),

    # Regarding user details
    path('user/', views.get_current_user, name="user"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('login/', views.APILoginView.as_view(), name="login"),
    path('logout/', views.api_logout, name="logout"),
    path('register/', views.APISignupView.as_view(), name='register'),
    path('sell/', views.SellerView.as_view(), name='sell'),

    # Cart, Orders related views
    path('cart/', views.CartView.as_view(), name='cart'),
    path('orders/', views.OrderView.as_view(), name='orders'),
    path('address/', views.APIBillingAddress.as_view(), name='orders'),
]

medical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from medicines.sitemaps import MedSiteMap
from accounts.sitemaps import AccountSiteMap
from django.views.generic import TemplateView
from .sitemaps import StaticSitemap


sitemaps = {
    'accounts': AccountSiteMap,
    'medicines': MedSiteMap,
    'other': StaticSitemap
}

urlpatterns = [
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots"),
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name="sitemap_url"),
    path("", include("home.urls")),
    path("", include("cart.urls")),
    path('admin/', admin.site.urls),
    path('medicines/', include("medicines.urls")),
    path("", include("checkout.urls")),
    path("", include("accounts.urls")),
    path("", include("allauth.urls")),
    path("api/v1/", include("api.urls")),
]

accounts/models.py
from neomodel import StructuredNode, StringProperty, RelationshipTo, PositiveIntegerProperty, RelationshipFrom
from django.conf import settings

class UserNode(StructuredNode):
    username = StringProperty(unique_index=True)
    first_name = StringProperty()
    last_name = StringProperty()

class UserProfileNode(StructuredNode):
    gender = StringProperty(choices=["Male", "Female", "Prefer not to say"], required=False)
    phone = PositiveIntegerProperty(verbose_name="Mobile Number", required=False)

    # Define relationships
    user = RelationshipTo(UserNode, 'HAS_PROFILE')

    def __str__(self):
        return f"{self.user.username} Profile"

    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

class SellerProfileNode(StructuredNode):
    store_name = StringProperty()
    address = StringProperty(max_length=40, required=False)
    pincode = PositiveIntegerProperty()

    # Define relationships
    user = RelationshipTo(UserNode, 'HAS_SELLER_PROFILE')

    def __str__(self):
        return f"Seller {self.user.username} Profile"

accounts/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import UserProfile, SellerProfile


class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ("first_name", "last_name")


class ProfileForm(ModelForm):

    class Meta:
        model = UserProfile
        exclude = ("user", )


class SellerForm(ModelForm):

    class Meta:
        model = SellerProfile
        exclude = ("user", )

accounts/views.py
import re
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.contrib.auth.models import Group
from django.contrib import messages
from .forms import UserForm, ProfileForm, SellerForm
from .models import UserProfile, SellerProfile
# Create your views here.


# noinspection PyArgumentList,PyArgumentList,PyArgumentList,PyArgumentList
@login_required
def profile(request: HttpRequest):
    """
    Handles profile changes and requests
    :param request: Request for profile details
    :type request: HttpRequest
    """
    if request.method == "POST":
        data = request.POST

        # data.get returns None by default ->
        first = data.get(key="first_name")
        last = data.get(key="last_name")
        gender = data.get(key="gender")
        phone = data.get(key="phone")

        if not re.match(r'^\d{10}$', phone):
            messages.error(request, "Phone must be Numeric and 10 characters in length")
        else:
            user = request.user
            user.first_name = first
            user.last_name = last
            user.save()
            try:
                user.userprofile.gender = gender
                user.userprofile.phone = phone
                user.userprofile.save()
                user.save()
            except ObjectDoesNotExist:
                prof = UserProfile(user=user, gender=gender, phone=phone)
                prof.save()

    user_data = UserForm(instance=request.user)
    profile_data = ProfileForm()
    seller = SellerForm()
    try:
        if request.user.userprofile:
            profile_data = ProfileForm(instance=UserProfile.objects.get(user=request.user))
            has_profile = True
        else:
            has_profile = False
    except ObjectDoesNotExist:
        has_profile = False
    try:
        seller = SellerForm(instance=request.user.sellerprofile)
    except ObjectDoesNotExist:
        pass
    ctx = {"user": user_data, "profile": profile_data, 'has_profile': has_profile,
           "is_seller": request.user.has_perm("medicines.add_medicine"), "seller": seller}
    return render(request, "accounts/profile.html", ctx)


@login_required
def be_seller(request):
    """
    Handles store details related data
    :type request: HttpRequest
    """
    if request.method == "POST":
        data = request.POST
        user = request.user
        store = data.get(key="store_name")
        address = data.get(key="address")
        pin = data.get(key="pincode")
        try:
            user.sellerprofile.store_name = store
            user.sellerprofile.address = address
            user.sellerprofile.pincode = pin
            user.sellerprofile.save()
            user.save()
            messages.success(request, "Your profile edited")
        except ObjectDoesNotExist:
            messages.success(request, "Congratulations! You are now seller at medstore")
            seller = SellerProfile(user=user, store_name=store, address=address, pincode=pin)
            seller.save()
        user.groups.add(Group.objects.get(name="Merchant"))
        user.save()
        return redirect("/profile/")

    seller = SellerForm()
    try:
        seller = SellerForm(instance=SellerProfile.objects.get(user=request.user))
    except ObjectDoesNotExist as e:
        print(e)

    ctx = {"seller": seller}
    return render(request, "accounts/apply.html", ctx)

accounts/templates/accounts/apply.html
{%extends 'base_bootstrap.html' %}
{% load crispy_forms_filters %}
{% block  head %}
<title>Seller account</title>
{% endblock %}
{% block welcome %}
<h1>Sell at MedStore</h1>
<p>Register your pharmacy below..</p>
{%endblock%}
{%block content%}
<form method="post">
    {%csrf_token%}
    {{seller|crispy}}
    <button type="submit" class="btn btn-primary float-right">Submit</button>
</form>
{%endblock%}

accounts/templates/accounts/profile.html
{%extends 'base_bootstrap.html' %}
{% load crispy_forms_filters %}
{%load crispy_forms_tags%}
{%load static%}
{%block head%}
    <title>{{request.user.username}} | MedStore</title>
    <meta name="description" content="{{request.user.username}} Profile on MedStore">
{%endblock%}
{%block content%}
<form method="post">
    {%csrf_token%}
    <div>
    <h2>Basic</h2><button type="button" class="btn float-right btn-primary" id="hide">Edit</button>
    {{user|crispy}}
    </div>
    <div>
    {{profile|crispy}}
    </div>
    <button class="btn float-right btn-success" id="submit" type="submit" style="display:none">Save Changes</button>
<a class="btn float-right btn-primary" style="margin-right: 1vw" href="{%url 'account_change_password'%}">Change Password</a>
</form>
    {%if is_seller and request.user.is_superuser%}
    <h2 style="clear:both">Seller Account</h2>
    <p><span style="color: red; font-style: italic">Note: </span>Click <a href="{%url 'Account:apply'%}"><em>here</em></a>
    to change your pharmacy details</p>
    {{seller|crispy}}
    {%elif request.user.is_superuser%}
    <section><h2>Welcome Boss</h2></section>
    <a type="button" href="{%url 'Account:apply'%}">Register Seller Profile</a>
    {%else%}
    <a type="button" href="{%url 'Account:apply'%}">Own a Pharmacy?... Apply for a seller account</a>
    {%endif%}
{%endblock%}
{%block js%}
<script src="{%static 'pikachu.js'%}"></script>
{%endblock%}