api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    # Medicines
    path('', views.MedicineView.as_view(), name="APIv1"),
    path('detail/<int:pk>/', views.APIDetailView.as_view(), name="medicine_detail"),
    path('detail/<str:slug>/', views.APIDetailView.as_view(), name="medicine_detail"),

    # Regarding user details
    path('user/', views.get_current_user, name="user"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('login/', views.APILoginView.as_view(), name="login"),
    path('logout/', views.api_logout, name="logout"),
    path('register/', views.APISignupView.as_view(), name='register'),
    path('sell/', views.SellerView.as_view(), name='sell'),

    # Cart, Orders related views
    path('cart/', views.CartView.as_view(), name='cart'),
    path('orders/', views.OrderView.as_view(), name='orders'),
    path('address/', views.APIBillingAddress.as_view(), name='orders'),
]

cart/urls.py
from django.urls import path
from .views import cartview, add_to_cart, remove_from_cart
from . import views

app_name = "cart"

urlpatterns = [
    path("cart/", cartview, name="home"),
    path("add/<slug>", add_to_cart, name="add"),
    path("remove/<slug>", remove_from_cart, name="remove"),
    path("increase/<slug>", views.increase_cart_test, name="increase"),
    path("decrease/<slug>", views.decrease_cart_test, name="decrease"),
    path("orders/", views.order_view, name="my_orders")
]

medical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from medicines.sitemaps import MedSiteMap
from accounts.sitemaps import AccountSiteMap
from django.views.generic import TemplateView
from .sitemaps import StaticSitemap


sitemaps = {
    'accounts': AccountSiteMap,
    'medicines': MedSiteMap,
    'other': StaticSitemap
}

urlpatterns = [
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots"),
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name="sitemap_url"),
    path("", include("home.urls")),
    path("", include("cart.urls")),
    path('admin/', admin.site.urls),
    path('medicines/', include("medicines.urls")),
    path("", include("checkout.urls")),
    path("", include("accounts.urls")),
    path("", include("allauth.urls")),
    path("api/v1/", include("api.urls")),
]

medicines/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name = "medicines"

urlpatterns = [
    path("", views.MedListView.as_view(), name="all"),
    path("medicine/<int:pk>/", views.MedDetailView.as_view(), name="detail"),
    path("add/", views.MedCreateView.as_view(success_url=reverse_lazy("medicines:all")), name="create"),
    path("update/<int:pk>/", views.MedUpdateView.as_view(success_url=reverse_lazy("medicines:all")), name="update"),
    path("delete/<int:pk>/", views.MedDeleteView.as_view(success_url=reverse_lazy("medicines:all")), name="delete"),
    path("medicine/<int:pk>/thumbnail/", views.stream_file, name="picture"),
]

medicines/models.py
from neomodel import StructuredNode, StringProperty, RelationshipTo, RelationshipFrom, FloatProperty, IntegerProperty, UniqueIdProperty, BooleanProperty

class MedCatNode(StructuredNode):
    name = StringProperty(unique_index=True)

class MedicineNode(StructuredNode):
    name = StringProperty()
    price = FloatProperty()
    quantity = IntegerProperty()
    thumbnail = StringProperty()
    thumb_content_type = StringProperty(default='image/png')
    description = StringProperty()
    slug = StringProperty(unique_index=True)
    created_at = StringProperty()
    updated_at = StringProperty()
    is_active = BooleanProperty(default=True)

    # Define relationships
    belongs_to = RelationshipTo(MedCatNode, 'BELONGS_TO')
    owned_by = RelationshipFrom('UserNode', 'OWNS')

    def as_json(self):
        owner = 'Medstore'
        if self.owned_by.is_connected():
            owner = self.owned_by.single().store_name

        return {
            'id': self.id,
            'name': self.name,
            'category': self.belongs_to.single().name,
            'price': self.price,
            'quantity': self.quantity,
            'description': self.description,
            'owner': owner,
            'slug': self.slug,
            'created_at': self.created_at,
            'updated_at': self.updated_at,
            'is_active': self.is_active
        }

medicines/forms.py
from django import forms
from .models import Medicine
from django.core.files.uploadedfile import InMemoryUploadedFile
from .humanize import naturalsize


class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024              # refers to 2MB
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    thumbnail = forms.FileField(required=False, label='Thumbnail to Upload <= ' + max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = Medicine
        fields = ['name', 'category', 'description', 'thumbnail', 'quantity', 'price']  # thumbnail is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('thumbnail')
        if not pic:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('thumbnail', "File must be < " + self.max_upload_limit_text + " bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.thumbnail  # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.thumbnail = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

api/views/medicine.py
from django.core.exceptions import ObjectDoesNotExist, FieldError
from django.http import JsonResponse, HttpRequest
from medicines.models import Medicine
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views.generic import View
from medicines.forms import CreateForm

# API Version 1

class MedicineView(View):
    @classmethod
    def get_queryset(cls, filters=None):
        # It's better to use this method separately, as we might want to do another queries,
        # or may need to order the data, or may need to sort the data, all of this will be
        # handled in this method
        """
        Expected keys:
            owner | category | price__lt | price__gt | quantity__gt | quantity__lt
        """
        m = Medicine.objects.all()
        for key, value in filters.items():
            try:
                if key == 'owner':
                    m = m.filter(owner__sellerprofile__store_name=value)
                elif key == 'category':
                    m = m.filter(category__name=value)
                else:
                    m = m.filter(key=value)
            except (FieldError, ValueError):
                pass
        return m

    def get(self, request: HttpRequest, *args, **kwargs) -> JsonResponse:
        """
        GET the medicines list
        :param request: request to get the list as json
        :type request: HttpRequest
        :return: List containing basic medicine data
        :rtype: JsonResponse
        """
        qs = self.get_queryset(request.GET)

        json = {med.id: {'name': med.name,
                         'price': med.price,
                         'category': med.category.name
                         } for med in qs}

        return JsonResponse(json)

    def post(self, request: HttpRequest) -> JsonResponse:
        """
        Create a medicine using formData

        :param request: request with the new medicine data
        :type request: HttpRequest
        :return: Respond if the query was successful
        :rtype: JsonResponse
        """

        if not self.request.user.has_perm('medicines.add_medicine'):
            return JsonResponse({'msg': "You don't have permission to update medicines"}, status=400)
        # Same process as the MedCreateView, but with customization for the JSON response
        form = CreateForm(request.POST, request.FILES or None)
        if not form.is_valid():
            return JsonResponse({'msg': 'This form has invalid data', 'errors': form.errors}, status=200)

        # Check if this request is duplicated

        temp = Medicine.objects.filter(name=form.data['name'], owner=self.request.user)

        if temp:
            return JsonResponse({'msg': 'No two medicines by the same owner can have the same'
                                        'name'}, status=400)

        med = form.save(commit=False)
        med.owner = self.request.user
        med.save()
        return JsonResponse({'msg': 'created', 'newID': med.id}, status=201)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        # Just to turn off the csrf verification for this view only...
        # In future, another ( process | algorithm | method ) must be incorporated without blocking
        # the CSRF
        return super().dispatch(request, *args, **kwargs)


class APIDetailView(View):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None

    @classmethod
    def get_med(cls, pk=None, slug=None):
        if pk is not None:
            med: Medicine = Medicine.objects.get(id=pk)
        else:
            med: Medicine = Medicine.objects.get(slug__exact=slug)
        return med

    def get(self, request, pk=None, slug=None):
        try:
            med = self.get_med(pk=pk, slug=slug)
            return JsonResponse(med.as_json)
        except ObjectDoesNotExist:
            return JsonResponse({'msg': 'Medicine not found'}, status=404)

    def post(self, request, pk=None, slug=None):
        try:
            med: Medicine = self.get_med(pk=pk, slug=slug)
            f = CreateForm(request.POST or None, request.FILES or None, instance=med)
            if f.is_valid():
                f.save()
                return JsonResponse({'msg': 'Got it', 'name': med.name})
            else:
                return JsonResponse({'msg': "No, you can't fool me", 'errors': f.errors})
        except ObjectDoesNotExist:
            return JsonResponse({'msg': "Are you kidding me?, that medicine doesn't exists at all"},
                                status=404)

medicines/views.py
from django.views.decorators.http import require_safe
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.urls import reverse_lazy
from .owner import *
from .models import Medicine
from .forms import CreateForm
from django.views import View
from .filters import ProductFilter
from cart.models import Order
from django.contrib.auth.mixins import PermissionRequiredMixin


# Create your views here.
class MedListView(OwnerListView):
    model = Medicine
    template_name = "medicines/medicine_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ProductFilter(self.request.GET, queryset=self.get_queryset())
        if self.request.user.is_authenticated:
            orders = Order.objects.filter(user=self.request.user, ordered=False)
            if orders.exists():
                cart_items = orders[0].items.all()
                a = [item.item for item in cart_items]
                context["items"] = a
        return context


class MedDetailView(OwnerDetailView):
    model = Medicine
    template_name = "medicines/medicine_detail.html"


class MedCreateView(LoginRequiredMixin, PermissionRequiredMixin, View):
    model = Medicine
    permission_required = 'medicines.add_medicine'
    permission_denied_message = "No Access"
    success_url = reverse_lazy("medicines:all")
    template_name = "medicines/medicine_add.html"

    def get(self, request):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = CreateForm(request.POST, request.FILES or None)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)
        med = form.save(commit=False)
        med.owner = self.request.user
        med.save()
        return redirect(self.success_url)


class MedUpdateView(LoginRequiredMixin, View):
    model = Medicine
    success_url = "medicines:all"
    template_name = "medicines/medicine_add.html"

    def get(self, request, pk):
        med = get_object_or_404(Medicine, id=pk, owner=self.request.user)
        form = CreateForm(instance=med)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk):
        med = get_object_or_404(Medicine, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=med)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)
        med = form.save(commit=False)
        med.save()
        return redirect(self.success_url)


class MedDeleteView(OwnerDeleteView):
    model = Medicine
    template_name = "medicines/medicine_delete.html"


@require_safe
def stream_file(request, pk):
    med = get_object_or_404(Medicine, id=pk)
    response = HttpResponse()
    if not med.thumbnail:
        return HttpResponse("No Thumbnail")
    response['Content-Type'] = med.thumb_content_type
    response['Content-Length'] = len(med.thumbnail)
    response.write(med.thumbnail)
    return response

medicines/templates/medicines/medicine_add.html
{% extends "base_bootstrap.html"%}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static%}
{%block head%}
<title>Add New Medicine Entry</title>
<meta name="description" content="Add a new medicine to our catalogue, SIgn up and create a
seller profile to access this feature">
{% endblock %}
{%block content%}
<form id="med_add" method="post" id="upload_form" enctype="multipart/form-data" class="form-group">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{%url 'medicines:all' %}'; return false;" value="Cancel">
</form>
{%endblock%}
{%block js%}
<script>
    document.querySelector('form#med_add').addEventListener('submit', function() {
      if (window.File && window.FileReader && window.FileList && window.Blob) {
          let file = document.querySelector('#id_thumbnail').files[0];
          if (file && file.size > {{ form.max_upload_limit }} ) {
              alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
          return false;
        }
      }
      return true;
    });
</script>
<script src="{%static 'pikachu.js'%}"></script>
{%endblock%}

medicines/templates/medicines/medicine_delete.html
{%extends "base_bootstrap.html"%}
{%block content%}
<h1>Delete Medicine Entry</h1>
<p>Are you sure you want to remove this medicine from catalog: {{medicine}}</p>
<form action="" method="post">
    {%csrf_token%}
    <input type="submit" value="Yes, Remove">
</form>
{%endblock%}

medicines/templates/medicines/medicine_detail.html
{% extends "base_bootstrap.html" %}
{% load static %}
{%block head%}
    <title>{{medicine}}|MedStore</title>
    <meta name="description" content="{{medicine}}|{{medicine.description|truncatewords:10}}">
    <link rel="stylesheet" href="{%static 'style.css'%}">
{%endblock%}
{% block content %}
    {% if medicine %}
        <div class="info">
        <h2>{{medicine.name}}(<span id="category">{{medicine.category}}</span>)</h2><br/>
        Info: <p>{{medicine.description}}</p>
        Price: {{medicine.price}}<br/>
        {%if medicine.quantity > 0%}
            Quantity: <span id="quantity">{{medicine.quantity}}</span><br/>
            </div>
            {%if medicine.thumbnail%}
                <div class="thumb">
                    <img src="{%url 'medicines:picture' medicine.id%}" alt="{{ medicine.name }} thumbnail" height="15%" width="15%">
                </div>
        {%endif%}
        {%else%}
            <p>Not available right Now :(</p>
        {%endif%}
        {%else%}
            <p>Invalid</p>
    {%endif%}
    <a href="{%url 'medicines:all' %}">Back to catalog</a>
{% endblock%}

medicines/templates/medicines/medicine_list.html
{% extends 'base_bootstrap.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{%load static%}
{%block head%}
<title>Medicines | MedStore</title>
<meta name="description" content="List of available medicines on a project site MedStore">
<link rel="stylesheet" href="{% static 'style.css' %}">
{%endblock%}
{% block content %}
<div class="container my-5">
   <h2 class="my-5">Featured Products</h2>
   <div class="row">
      <div class="col-md-3">
         <form method="get">
            {{ filter.form| crispy }}
            <button class="btn btn-secondary container" type="submit">Search</button>
         </form>
      </div>
      <div class="col-md-9">
         <div class="row">
            {% for med in filter.qs %}
            <div class="col-md-6 col-sm-12 col-lg-4">
               <div class="product">
                    <img src="{%url 'medicines:picture' med.id%}" class="product_image" alt="{{med}}">
                   <div class="desc">
                       <a href="{%url 'medicines:detail' med.id%}"><span>{{med}} <br/>
                           {{med.quantity}} available</span><br/></a>
                    </div>
                    <div>
                        <span class="price" style="padding: 25px;">&#8377; {{med.price}}</span>
                        {%if request.user.is_authenticated%}
                        <br/>
                        {%if med in items%}
                        <a href="{%url 'cart:remove' med.slug%}" class="btn btn-danger float-right">Remove from Cart</a>
                        {%else%}
                        <a href="{%url 'cart:add' med.slug%}" class="btn btn-success float-right">Add to Cart</a>
                        {%endif%}
                        {%endif%}
                    </div>
                </div>
                <hr>

               <!-- card // -->
            </div>
            <!-- col // -->
             {%empty%}
                <h3>No Medicines Available</h3>
            {% endfor %}
         </div>
      </div>
   </div>
</div>
{% endblock %}
{% block js %}

{% endblock %}